echo Create primary database....
prodb primary sports
echo Add ai extents....
prostrct add primary ai.st
echo List structure....
prostrct list primary
echo Mark as backed up....
rfutil primary -C mark backedup
echo Begin After Imaging....
proutil primary -C aimage begin
echo Enable aiarchiver
proutil primary -C aiarchiver enable
echo Enable Site Replication as Source....
proutil primary -C enablesitereplication source
echo Make a backup....
probkup primary db.bak
echo Copy backup to secondary....
cp db.bak ../secondary
cp db.bak ../tertiary
echo FINISHED!

