echo Restore database....
prorest tertiary db.bak
echo Add ai extents....
prostrct add tertiary ai.st
echo List new structure....
prostrct list tertiary
echo Enable AI....
proutil tertiary -C aimage begin
echo Enable aiarchiver....
proutil tertiary -C aiarchiver enable
echo Enable for target replication...
proutil tertiary -C enablesitereplication target
echo FINISHED!
